#server:
#  port: 8888
#  servlet:
#    context-path: /project
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project
    password: project123
    url: jdbc:mysql://rm-2ze9pu9eny1mjwt68so.mysql.rds.aliyuncs.com:3306/project?serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath*:mapper/*.xml
